# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Identify for every point in the rasterised decision space the corresponding basin it belongs to.
#'
#' @param efficientSets A list containing for every efficient set the indices of all efficient points.
#' @param gradients A vector containing the accumulated gradients for every point in the grid.
#' @param gridSize The side length of the grid.
#' @param nDim The number of dimensions in the decision space.
#' @export
getBasinLabels <- function(efficientSets, gradients, gridSize, nDim) {
    .Call(`_ABSE_getBasinLabels`, efficientSets, gradients, gridSize, nDim)
}

#' For a vector of indices with efficient points within a grid identify efficient sets.
#'
#' @param efficientPoints The vector containing the indices of all efficient points.
#' @param gridSize The side length of the grid.
#' @param nDim The number of dimensions in the decision space.
#' @export
getEfficientSets <- function(efficientPoints, gridSize, nDim) {
    .Call(`_ABSE_getEfficientSets`, efficientPoints, gridSize, nDim)
}

