# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

filterByBasin <- function(solutions, basinLabels, boudaries, gridSize, nDim) {
    .Call(`_bbe_filterByBasin`, solutions, basinLabels, boudaries, gridSize, nDim)
}

getBasinLabelsCPP <- function(efficientSets, lastVisited) {
    .Call(`_bbe_getBasinLabelsCPP`, efficientSets, lastVisited)
}

getEfficientSets <- function(efficientPoints, gridSize, nDim, domSort = FALSE, rank = as.numeric( c()), nRank = 0L, joinFronts = FALSE) {
    .Call(`_bbe_getEfficientSets`, efficientPoints, gridSize, nDim, domSort, rank, nRank, joinFronts)
}

